name: Run Unit Tests on Push

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint # Replace with your actual ESLint command if it's different

      - name: Run Prettier
        run: npm run format

      - name: Run Unit Tests
        run: npm test
